#' ChatGPT: Rephrase text
#'
#' @param code The code to be explained by ChatGPT. If not provided, it will use what's copied on
#'   the clipboard.
#'
#' @examples
#' \dontrun{
#' cat(explain_code("for (i in 1:10) {\n  print(i ** 2)\n}"))
#' }
#'
#' @importFrom clipr read_clip
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
rephrase_text <- function(code = clipr::read_clip(allow_non_interactive = TRUE)) {
  code <- paste(gsub('"', "'", code), collapse = "\n") # TODO promt
  prompt <- paste0('Rephrase the following text in english, assuming you are an academic and this text aims to appear in an economic, econometric or financial journal study (do not mention this in the text)\n\n```\n', code, '\n```')
  parse_response(gpt_get_completions(prompt))
}
